/*
 * Copyright (c) 2018, Loong Wan (https://github.com/loong10k).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.cxf.endpoint.jaxrs.definition;

import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HEAD;
import jakarta.ws.rs.OPTIONS;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;

/**
 * Descriptor for a single REST endpoint method generated by the
 * {@link org.apache.cxf.endpoint.jaxrs.JaxrsEndpointApiCtClassBuilder}
 * family of builders.
 *
 * <p>The descriptor bundles the {@linkplain #getMethod() HTTP verb},
 * {@linkplain #getName() Java method name} and {@linkplain #getPath()
 * JAX-RS URI template} that should be attached to the generated
 * method, along with optional {@code @Consumes} and {@code @Produces}
 * media-type lists.</p>
 *
 * @author <a href="https://github.com/loong10k">Loong Wan</a>
 * @since 3.0.0
 * @see HttpMethodEnum
 * @see jakarta.ws.rs.Path
 * @see jakarta.ws.rs.Consumes
 * @see jakarta.ws.rs.Produces
 */
public class RestMethod {

	/**
	 * Java 方法的名称
	 */
	private final String name;

	/**
	 * Associates the name of a HTTP method with an annotation.
	 * @see GET
	 * @see POST
	 * @see PUT
	 * @see DELETE
	 * @see PATCH
	 * @see HEAD
	 * @see OPTIONS
	 */
	private final HttpMethodEnum method;

	/**
	 * Identifies the URI path that a resource class or class method will serve
	 * requests for.
	 * 
	 * @see jakarta.ws.rs.Path
	 */
	private final String path;

	/**
	 * A list of media types. Each entry may specify a single type or consist of a
	 * comma separated list of types, with any leading or trailing white-spaces in a
	 * single type entry being ignored. For example:
	 * 
	 * <pre>
	 * { "image/jpeg, image/gif ", " image/png" }
	 * </pre>
	 * 
	 * Use of the comma-separated form allows definition of a common string constant
	 * for use on multiple targets.
	 */
	private String[] mediaTypes = new String[] { "*/*" };
	
	/**
	 * Defines the media types that the methods of a resource class or
	 * {@link jakarta.ws.rs.ext.MessageBodyReader} can accept.
	 * 
	 * @see jakarta.ws.rs.Consumes
	 */
	private String[] consumes;

	/**
     * Builds a descriptor without {@code @Consumes} media types. The
     * generated method will still receive the default {@code @Produces}
     * value ({@code *&#47;*}).
     *
     * @param method HTTP verb for this method.
     * @param name   Java method name.
     * @param path   URI template appended to the resource path.
     */
	public RestMethod(HttpMethodEnum method, String name, String path) {
		this.method = method;
		this.name = name;
		this.path = path;
	}

    /**
     * Builds a descriptor that also declares the supplied
     * {@code @Consumes} media types.
     *
     * @param method   HTTP verb for this method.
     * @param name     Java method name.
     * @param path     URI template appended to the resource path.
     * @param consumes media types accepted by this method.
     */
	public RestMethod(HttpMethodEnum method, String name, String path, String... consumes) {
		this.method = method;
		this.name = name;
		this.path = path;
		this.consumes = consumes;
	}

    /**
     * Returns the {@code @Consumes} media types declared by this
     * descriptor.
     *
     * @return the consumed media types, possibly {@code null}.
     */
	public String[] getConsumes() {
		return consumes;
	}

    /**
     * Returns the {@code @Produces} media types declared by this
     * descriptor. Defaults to a single {@code *&#47;*} entry.
     *
     * @return the produced media types, never {@code null}.
     */
	public String[] getMediaTypes() {
		return mediaTypes;
	}

    /**
     * Replaces the {@code @Produces} media types.
     *
     * @param mediaTypes new produced media types.
     */
	public void setMediaTypes(String[] mediaTypes) {
		this.mediaTypes = mediaTypes;
	}

    /**
     * Replaces the {@code @Consumes} media types.
     *
     * @param consumes new consumed media types.
     */
	public void setConsumes(String[] consumes) {
		this.consumes = consumes;
	}

    /**
     * Returns the Java method name.
     *
     * @return the method name.
     */
	public String getName() {
		return name;
	}

    /**
     * Returns the HTTP verb.
     *
     * @return the verb, never {@code null}.
     */
	public HttpMethodEnum getMethod() {
		return method;
	}

    /**
     * Returns the URI template that follows the class-level
     * {@code @Path}.
     *
     * @return the URI template.
     */
	public String getPath() {
		return path;
	}

}
